server:
  port: 9696
book.url: http://localhost:8080
user.url: http://localhost:8087
ticket.url: http://localhost:8083
spring:
  jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false
  cache:
    cache-names: searchBook, searchBookByStatus, searchBookById
    caffeine:
      spec: maximumSize=500, expireAfterAccess=60s